### ISSUE TITLE
conda command not found

### ISSUE THREAD

**Issue by jayhsu0627** [hangvane/cuda-conda-desktop#1]
Hi,
After initialized your docker container, type in `conda`. shows command not found.

User need to `source ~/.bash_profile` but the bash_profile doesn't exist. we need to forced add environmental parameters

`export PATH=~/miniconda3/bin:$PATH`

Could you solve this problem?

**Comment by hangvane** [comment]
I'm sorry for my neglect of this project.

It seems that this problem will come up only when you use `docker exec` to open the terminal of container. To fix this problem, I added an `ENV` parameter in the Dockerfile([link](https://github.com/hangvane/cuda-conda-desktop/blob/77b60809251d07f975b9321b1d248d66f3a002a2/dist/ubuntu16.04/Dockerfile#L6)) and it seems the problem is solved. Besides, I recommend you to connect this container via SSH and the problem would not occur in this way.

Please reply if you have any other problems, thank you!
